### ISSUE TITLE
Update fork from upstream repository

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/kube-metrics-adapter#22]
**Is your feature request related to a problem? Please describe.**
There are quite a few changes in the upstream repository.

**Describe the solution you'd like to see**
Let's update the project.

**Describe alternatives you've considered**
Do we still need this fork? If not, can we switch to the upstream version? Can we contribute back the necessary changes?

**Comment by sancyx** [comment]
Created related ticket to remove support for hpa-operator: https://github.com/banzaicloud/pipeline/issues/3397
